# Makefile for cs 455 C++ Debugger / Linked lists lab


factors: factors.cpp
	g++ -ggdb -Wall factors.cpp -o factors

factors_fix: factors_fix.cpp
	g++ -ggdb -Wall factors_fix.cpp -o factors_fix

testlist: testlist.cpp
	g++ -ggdb -Wall testlist.cpp -o testlist

testlist_fix_sumList: testlist_fix_sumList.cpp
	g++ -ggdb -Wall testlist_fix_sumList.cpp -o testlist_fix_sumList

testlist_fix_append: testlist_fix_append.cpp
	g++ -ggdb -Wall testlist_fix_append.cpp -o testlist_fix_append

testlist_fixed: testlist_fixed.cpp
	g++ -ggdb -Wall testlist_fixed.cpp -o testlist_fixed